"""empty message

Revision ID: 03e4a8076080
Revises: b9fc4b827258
Create Date: 2018-01-26 15:13:15.240507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e4a8076080'
down_revision = 'b9fc4b827258'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column(
        'rating_count', sa.Integer(), nullable=True))
    op.drop_column('movie', 'rating_cout')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column(
        'rating_cout', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('movie', 'rating_count')
    # ### end Alembic commands ###


def upgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
