"""empty message

Revision ID: 091742d2edf1
Revises: 03e4a8076080
Create Date: 2018-01-26 17:46:56.046150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091742d2edf1'
down_revision = '03e4a8076080'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'genre',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('movie_id', sa.BigInteger(), nullable=True),
        sa.Column('value', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    # ### end Alembic commands ###


def upgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
