"""empty message

Revision ID: 13db7779cb06
Revises: 70b9ccb48407
Create Date: 2018-01-24 16:21:32.646797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13db7779cb06'
down_revision = '70b9ccb48407'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'distance',
        sa.Column('first_movie_id', sa.BigInteger(), nullable=False),
        sa.Column('second_movie_id', sa.BigInteger(), nullable=False),
        sa.Column('value', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['first_movie_id'], ['movie.id'], ),
        sa.ForeignKeyConstraint(['second_movie_id'], ['movie.id'], ),
        sa.PrimaryKeyConstraint('first_movie_id', 'second_movie_id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distance')
    # ### end Alembic commands ###


def upgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
