"""empty message

Revision ID: 148ca5b1356a
Revises: b7652c4a9a92
Create Date: 2017-10-21 16:31:18.532073

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '148ca5b1356a'
down_revision = 'b7652c4a9a92'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'showing', sa.Column('google_place_id', sa.String(), nullable=True))
    op.alter_column(
        'showing', 'geometry', type_=geoalchemy2.types.Geography(
            geometry_type='POINT', srid=4326, spatial_index=False))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showing', 'google_place_id')
    op.alter_column(
        'showing', 'geometry', type_=geoalchemy2.types.Geography(
            geometry_type='POLYGON', srid=4326, spatial_index=False))
    # ### end Alembic commands ###


def upgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
