"""empty message

Revision ID: 4a0783d40abb
Revises:
Create Date: 2017-10-10 01:24:02.631445

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4a0783d40abb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cell',
        sa.Column('cell_id', sa.BigInteger(), nullable=False),
        sa.Column('region', sa.String(), nullable=False),
        sa.Column('cell_name', sa.String(), nullable=False),
        sa.Column(
            'geometry',
            geoalchemy2.types.Geography(
                geometry_type='POLYGON', srid=4326, spatial_index=False),
            nullable=True),
        sa.PrimaryKeyConstraint('cell_id')
    )
    op.create_index('idx_cell_geometry', 'cell', ['geometry'],
                    unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cell_geometry', table_name='cell')
    op.drop_table('cell')
    # ### end Alembic commands ###
