"""empty message

Revision ID: 52778e86e919
Revises:
Create Date: 2017-10-10 01:38:04.853651

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '52778e86e919'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cinema',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('website', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column(
            'geometry',
            geoalchemy2.types.Geography(
                geometry_type='POLYGON', srid=4326, spatial_index=False),
            nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'idx_cinema_geometry',
        'cinema', ['geometry'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cinema_geometry', table_name='cinema')
    op.drop_table('cinema')
    # ### end Alembic commands ###
