"""empty message

Revision ID: 62c7982b2667
Revises: b4105f313b7e
Create Date: 2017-10-19 23:38:27.292811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c7982b2667'
down_revision = 'b4105f313b7e'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column(
        'movie', sa.Column('last_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'last_modified')
    op.drop_column('movie', 'created')
    # ### end Alembic commands ###


def upgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invites', ['email'])
    # ### end Alembic commands ###


def downgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='unique')
    # ### end Alembic commands ###
