"""empty message

Revision ID: 835ba34251ee
Revises: a471cac446c7
Create Date: 2018-01-26 14:15:52.367424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835ba34251ee'
down_revision = 'a471cac446c7'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column(
        'favorite_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'favorite_count')
    # ### end Alembic commands ###


def upgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
