"""empty message

Revision ID: 89073f4c8213
Revises: b543f5bd5883
Create Date: 2017-10-16 14:44:54.979357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89073f4c8213'
down_revision = 'b543f5bd5883'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def upgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'invites',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('claimed', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('admin', sa.Column('email', sa.String(), nullable=False))
    op.add_column(
        'admin', sa.Column('otp_secret', sa.String(length=16), nullable=False))
    op.add_column('admin', sa.Column('password', sa.String(), nullable=False))
    op.add_column('admin', sa.Column('username', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'admin', ['username'])
    op.create_unique_constraint(None, 'admin', ['email'])
    # ### end Alembic commands ###


def downgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin', type_='unique')
    op.drop_constraint(None, 'admin', type_='unique')
    op.drop_column('admin', 'username')
    op.drop_column('admin', 'password')
    op.drop_column('admin', 'otp_secret')
    op.drop_column('admin', 'email')
    op.drop_table('invites')
    # ### end Alembic commands ###
