"""empty message

Revision ID: a471cac446c7
Revises: b9e4f76babb8
Create Date: 2018-01-26 00:15:03.334561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a471cac446c7'
down_revision = 'b9e4f76babb8'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('avg_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'avg_rating')
    # ### end Alembic commands ###


def upgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
