"""empty message

Revision ID: a5af8aa2a107
Revises: 52778e86e919
Create Date: 2017-10-12 16:14:59.522600

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a5af8aa2a107'
down_revision = '52778e86e919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'movie',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'showing',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('website', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column(
            'geometry',
            geoalchemy2.types.Geography(
                geometry_type='POLYGON', srid=4326, spatial_index=False),
            nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'idx_showing_geometry', 'showing', ['geometry'],
        unique=False, postgresql_using='gist')
    op.create_table(
        'movie_showing',
        sa.Column('movie_id', sa.BigInteger(), nullable=False),
        sa.Column('showing_id', sa.BigInteger(), nullable=False),
        sa.Column('time_from', sa.DateTime(), nullable=True),
        sa.Column('time_to', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
        sa.ForeignKeyConstraint(['showing_id'], ['showing.id'], ),
        sa.PrimaryKeyConstraint('movie_id', 'showing_id')
    )
    op.drop_table('cinema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cinema',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            'description', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            'geometry',
            geoalchemy2.types.Geography(geometry_type='POLYGON', srid=4326),
            autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='cinema_pkey')
    )
    op.drop_table('movie_showing')
    op.drop_index('idx_showing_geometry', table_name='showing')
    op.drop_table('showing')
    op.drop_table('movie')
    # ### end Alembic commands ###
