"""empty message

Revision ID: b4105f313b7e
Revises: 89073f4c8213
Create Date: 2017-10-17 11:30:36.668202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = 'b4105f313b7e'
down_revision = '89073f4c8213'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def upgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'admin', sa.Column('two_factor', sa.Boolean(), nullable=True))
    op.execute(
        table('admin', column('two_factor')).update().values(two_factor=False))
    op.alter_column('admin', 'two_factor', nullable=False)
    # ### end Alembic commands ###


def downgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'two_factor')
    # ### end Alembic commands ###
