"""empty message

Revision ID: c276af09264f
Revises: 091742d2edf1
Create Date: 2018-01-26 23:31:58.271983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c276af09264f'
down_revision = '091742d2edf1'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'showing_movie',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('movie_id', sa.BigInteger(), nullable=False),
        sa.Column('showing_id', sa.BigInteger(), nullable=False),
        sa.Column('time_from', sa.DateTime(), nullable=True),
        sa.Column('time_to', sa.DateTime(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
        sa.ForeignKeyConstraint(['showing_id'], ['showing.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('movie_showing')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'movie_showing',
        sa.Column(
            'movie_id', sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            'showing_id', sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            'time_from', postgresql.TIMESTAMP(),
            autoincrement=False, nullable=True),
        sa.Column(
            'time_to', postgresql.TIMESTAMP(),
            autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ['movie_id'], ['movie.id'], name='movie_showing_movie_id_fkey'),
        sa.ForeignKeyConstraint(
            ['showing_id'], ['showing.id'],
            name='movie_showing_showing_id_fkey'),
        sa.PrimaryKeyConstraint(
            'movie_id', 'showing_id',
            name='movie_showing_pkey')
    )
    op.drop_table('showing_movie')
    # ### end Alembic commands ###


def upgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
